resolver: lts-20.26

docker:
    enable: true

nix:
    enable: false

packages:
    - '.'

extra-deps:
    - webdriver-w3c-0.0.3
    - script-monad-0.0.3
    - crypton-0.33

flags: {}

extra-package-dbs: []
