name: "Browser tests on web-push-example"
on:
  pull_request:
  push:
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: cachix/install-nix-action@v22
      with:
        github_access_token: ${{ secrets.GITHUB_TOKEN }}
    - uses: cachix/cachix-action@v12
      with:
        name: web-push
        authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
    - uses: DeterminateSystems/magic-nix-cache-action@v2
    - run: nix build .#web-push-example-test
    - run: nix run .#web-push-example-test